import { useEffect, useState, type FormEvent } from 'react'
import { authenticatedFetch } from './api.ts'
import { isChallengesResponse, type ChallengeMetric, type ChallengesResponse } from './challengesApi.ts'
import type { FriendshipItem } from './friendsApi.ts'

type Props = { profileId: string; friends: FriendshipItem[] }
const metricLabels: Record<ChallengeMetric, string> = { ROUND_COUNT: 'Most rounds', STABLEFORD_POINTS: 'Most Stableford points', LOWEST_GROSS_SCORE: 'Lowest average gross score' }
const today = new Date()
const defaultStartDate = today.toISOString().slice(0, 10)
const defaultEndDate = new Date(today.getTime() + 30 * 86400000).toISOString().slice(0, 10)

export default function ChallengesBoard({ profileId, friends }: Props) {
  const [data, setData] = useState<ChallengesResponse | null>(null)
  const [opponentId, setOpponentId] = useState('')
  const [metric, setMetric] = useState<ChallengeMetric>('ROUND_COUNT')
  const [startsOn, setStartsOn] = useState(defaultStartDate)
  const [endsOn, setEndsOn] = useState(defaultEndDate)
  const [error, setError] = useState('')
  const [refresh, setRefresh] = useState(0)
  useEffect(() => { const controller = new AbortController(); void authenticatedFetch('/api/users/me/challenges', { signal: controller.signal }).then(async (response) => { const body: unknown = await response.json().catch(() => null); if (!response.ok || !isChallengesResponse(body)) throw new Error('We could not load challenges.'); if (!controller.signal.aborted) setData(body) }).catch((value: unknown) => { if (!controller.signal.aborted) setError(value instanceof Error ? value.message : 'We could not load challenges.') }); return () => controller.abort() }, [profileId, refresh])
  async function createChallenge(event: FormEvent) { event.preventDefault(); setError(''); const response = await authenticatedFetch('/api/users/me/challenges', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ opponentId, metric, startsOn, endsOn }) }); if (!response.ok) return setError('We could not create that challenge.'); setOpponentId(''); setRefresh((value) => value + 1) }
  async function update(id: string, action: 'accept' | 'decline' | 'cancel') { setError(''); const response = await authenticatedFetch(`/api/users/me/challenges/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action }) }); if (!response.ok) return setError('We could not update that challenge.'); setRefresh((value) => value + 1) }
  return <section className="friend-section challenge-board" aria-labelledby="challenges-title"><h2 id="challenges-title">Challenges and leaderboards</h2><p className="round-tags-intro">Invite an accepted friend. Only verified individual rounds played inside the date window count.</p><form className="challenge-form" onSubmit={(event) => void createChallenge(event)}><label>Friend<select required value={opponentId} onChange={(event) => setOpponentId(event.target.value)}><option value="">Choose a friend</option>{friends.map((item) => <option key={item.player.id} value={item.player.id}>{item.player.name}</option>)}</select></label><label>Leaderboard<select value={metric} onChange={(event) => setMetric(event.target.value as ChallengeMetric)}>{Object.entries(metricLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Starts<input type="date" value={startsOn} onChange={(event) => setStartsOn(event.target.value)} /></label><label>Ends<input type="date" value={endsOn} onChange={(event) => setEndsOn(event.target.value)} /></label><button type="submit" disabled={!opponentId}>Send challenge</button></form>{error ? <p className="friends-alert is-error" role="alert">{error}</p> : null}<div className="challenge-list">{data?.challenges.map((challenge) => { const incoming = challenge.opponentId === profileId; return <article key={challenge.id} className="challenge-card"><header><div><strong>{metricLabels[challenge.metric]}</strong><small>{challenge.startsOn} to {challenge.endsOn}</small></div><span>{challenge.status.toLowerCase()}</span></header><ol>{challenge.standings.map((standing) => <li key={standing.player.id}><span>{standing.player.name}<small>{standing.player.homeClub?.name ?? 'Home club not set'}</small></span><strong>{standing.score ?? '—'}</strong></li>)}</ol>{challenge.status === 'PENDING' && incoming ? <div className="challenge-actions"><button type="button" onClick={() => void update(challenge.id, 'accept')}>Accept</button><button type="button" className="is-secondary" onClick={() => void update(challenge.id, 'decline')}>Decline</button></div> : null}{challenge.creatorId === profileId && (challenge.status === 'PENDING' || challenge.status === 'ACTIVE') ? <button type="button" className="is-secondary" onClick={() => void update(challenge.id, 'cancel')}>Cancel challenge</button> : null}</article> })}{data?.challenges.length === 0 ? <p className="friends-empty">No challenges yet.</p> : null}</div></section>
}
