import { useEffect, useState, type FormEvent } from 'react'
import { authenticatedFetch } from './api.ts'
import type { FriendshipItem } from './friendsApi.ts'
import { isRoundSharesResponse, type RoundSharesResponse } from './sharedRoundsApi.ts'

export default function SharedRounds({ profileId, friends }: { profileId: string; friends: FriendshipItem[] }) {
  const [data, setData] = useState<RoundSharesResponse | null>(null)
  const [roundId, setRoundId] = useState('')
  const [recipientId, setRecipientId] = useState('')
  const [error, setError] = useState('')
  const [refresh, setRefresh] = useState(0)
  useEffect(() => { const controller = new AbortController(); void authenticatedFetch('/api/users/me/round-shares', { signal: controller.signal }).then(async (response) => { const body: unknown = await response.json().catch(() => null); if (!response.ok || !isRoundSharesResponse(body)) throw new Error('We could not load shared rounds.'); if (!controller.signal.aborted) setData(body) }).catch((value: unknown) => { if (!controller.signal.aborted) setError(value instanceof Error ? value.message : 'We could not load shared rounds.') }); return () => controller.abort() }, [profileId, refresh])
  async function share(event: FormEvent) { event.preventDefault(); setError(''); const response = await authenticatedFetch('/api/users/me/round-shares', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ roundId, recipientId }) }); if (!response.ok) return setError('We could not share that round. It may already be shared.'); setRoundId(''); setRecipientId(''); setRefresh((value) => value + 1) }
  async function remove(id: string) { setError(''); const response = await authenticatedFetch(`/api/users/me/round-shares/${encodeURIComponent(id)}`, { method: 'DELETE' }); if (!response.ok) return setError('We could not remove that shared round.'); setRefresh((value) => value + 1) }
  return <section className="friend-section shared-rounds" aria-labelledby="shared-rounds-title"><h2 id="shared-rounds-title">Shared rounds</h2><p className="round-tags-intro">Choose exactly who can see a score summary and hole-by-hole card. Notes, photos, and account details stay private.</p><form className="shared-round-form" onSubmit={(event) => void share(event)}><label>Round<select required value={roundId} onChange={(event) => setRoundId(event.target.value)}><option value="">Choose a round</option>{data?.availableRounds.map((round) => <option key={round.id} value={round.id}>{round.datePlayed} · {round.tee.course.club.name} · {round.tee.course.name}</option>)}</select></label><label>Friend<select required value={recipientId} onChange={(event) => setRecipientId(event.target.value)}><option value="">Choose a friend</option>{friends.map((item) => <option key={item.player.id} value={item.player.id}>{item.player.name}</option>)}</select></label><button type="submit" disabled={!roundId || !recipientId}>Share round</button></form>{error ? <p className="friends-alert is-error" role="alert">{error}</p> : null}<div className="shared-round-list">{data?.shares.map((share) => <details className="shared-round-card" key={share.id}><summary><span><strong>{share.round.tee.course.club.name} · {share.round.tee.course.name}</strong><small>{share.round.datePlayed} · {share.direction === 'INCOMING' ? `Shared by ${share.round.user.name}` : `Shared with ${share.recipient.name}`}</small></span><strong>{share.round.scoringFormat === 'STABLEFORD' ? `${share.round.stablefordPoints ?? '—'} pts` : share.round.grossScore ?? 'Record only'}</strong></summary><div className="shared-round-detail"><p>{share.round.holeCount} holes · {share.round.tee.teeName} tees{share.round.scoreDifferential === null ? '' : ` · Differential ${share.round.scoreDifferential.toFixed(1)}`}</p>{share.round.holeScores.length > 0 ? <div className="shared-hole-grid">{share.round.holeScores.map((hole) => <span key={hole.holeNumber}><small>Hole {hole.holeNumber} · Par {hole.par} · SI {hole.strokeIndex}</small><strong>{hole.pickedUp ? 'Picked up' : hole.strokesTaken}</strong></span>)}</div> : <p>No hole-by-hole scores were recorded.</p>}<button className="is-secondary" type="button" onClick={() => void remove(share.id)}>{share.direction === 'OUTGOING' ? 'Revoke access' : 'Remove from shared rounds'}</button></div></details>)}{data?.shares.length === 0 ? <p className="friends-empty">No rounds have been shared yet.</p> : null}</div></section>
}
