import { useEffect, useState, type FormEvent } from 'react'
import { authenticatedFetch } from './api.ts'
import { isTournamentSeriesResponse, type TournamentSeries } from './tournamentSeriesApi.ts'

export default function TournamentSeriesResults({ profileId }: { profileId: string }) {
  const [series, setSeries] = useState<TournamentSeries[]>([]), [message, setMessage] = useState(''), [error, setError] = useState(''), [refresh, setRefresh] = useState(0)
  useEffect(() => { const controller = new AbortController(); void authenticatedFetch('/api/users/me/tournament-series', { signal: controller.signal }).then(async (response) => { const body: unknown = await response.json(); if (response.ok && isTournamentSeriesResponse(body) && !controller.signal.aborted) setSeries(body.series.filter((item) => item.isOrganizer && item.status === 'ACTIVE')) }).catch(() => undefined); return () => controller.abort() }, [profileId, refresh])
  async function save(event: FormEvent<HTMLFormElement>, item: TournamentSeries, eventId: string) { event.preventDefault(); const data = new FormData(event.currentTarget); const results = item.members.filter((member) => member.status === 'ACCEPTED').flatMap((member) => { const position = data.get(`p-${member.userId}`), points = data.get(`v-${member.userId}`); return position && points !== '' ? [{ userId: member.userId, position: Number(position), points: Number(points) }] : [] }); const response = await authenticatedFetch(`/api/users/me/tournament-series/${item.id}/events/${eventId}/results`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ results }) }); const body: unknown = await response.json().catch(() => null); if (!response.ok) { setError(typeof body === 'object' && body !== null && 'error' in body ? String(body.error) : 'Results could not be saved.'); return } setError(''); setMessage('Event results saved.'); setRefresh((value) => value + 1) }
  const events = series.flatMap((item) => item.events.map((event) => ({ item, event })))
  if (!events.length) return null
  return <section className="friend-section tournament-series"><h2>Record series results</h2><p className="round-tags-intro">Enter a finishing position and points for each competitor who recorded a result.</p>{error ? <p className="friends-alert is-error" role="alert">{error}</p> : null}{message ? <p className="friends-alert" role="status">{message}</p> : null}<div className="series-events">{events.map(({ item, event }) => <article key={event.id}><strong>{item.name} · {event.name}</strong><form className="series-event-form" onSubmit={(formEvent) => void save(formEvent, item, event.id)}>{item.members.filter((member) => member.status === 'ACCEPTED').map((member) => { const saved = event.results.find((result) => result.userId === member.userId); return <label key={member.userId}>{member.user.name}<input name={`p-${member.userId}`} type="number" min="1" step="1" defaultValue={saved?.position ?? ''} placeholder="Position" /><input name={`v-${member.userId}`} type="number" min="0" step="0.01" defaultValue={saved?.points ?? ''} placeholder="Points" /></label> })}<button>Save event results</button></form></article>)}</div></section>
}
