export type SeriesPlayer = { id: string; name: string; homeClub: { id: string; name: string } | null }
export type SeriesMember = { userId: string; status: 'INVITED' | 'ACCEPTED' | 'DECLINED'; respondedAt: string | null; user: SeriesPlayer }
export type SeriesResult = { userId: string; position: number; points: number }
export type SeriesEvent = { id: string; name: string; playedOn: string; course: string | null; notes: string | null; results: SeriesResult[] }
export type SeriesStanding = { position: number; user: SeriesPlayer; eventsPlayed: number; wins: number; podiums: number; points: number }
export type TournamentSeries = { id: string; organizerId: string; name: string; description: string | null; status: 'DRAFT' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED'; isOrganizer: boolean; organizer: SeriesPlayer; members: SeriesMember[]; events: SeriesEvent[]; standings: SeriesStanding[]; createdAt: string; updatedAt: string }
export type TournamentSeriesResponse = { series: TournamentSeries[] }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null }
function player(value: unknown): value is SeriesPlayer { return record(value) && typeof value.id === 'string' && typeof value.name === 'string' && (value.homeClub === null || record(value.homeClub) && typeof value.homeClub.id === 'string' && typeof value.homeClub.name === 'string') }
function member(value: unknown): value is SeriesMember { return record(value) && typeof value.userId === 'string' && ['INVITED','ACCEPTED','DECLINED'].includes(String(value.status)) && (value.respondedAt === null || typeof value.respondedAt === 'string') && player(value.user) }
function result(value: unknown): value is SeriesResult { return record(value) && typeof value.userId === 'string' && Number.isInteger(value.position) && typeof value.points === 'number' }
function event(value: unknown): value is SeriesEvent { return record(value) && typeof value.id === 'string' && typeof value.name === 'string' && typeof value.playedOn === 'string' && (value.course === null || typeof value.course === 'string') && (value.notes === null || typeof value.notes === 'string') && Array.isArray(value.results) && value.results.every(result) }
function standing(value: unknown): value is SeriesStanding { return record(value) && Number.isInteger(value.position) && player(value.user) && Number.isInteger(value.eventsPlayed) && Number.isInteger(value.wins) && Number.isInteger(value.podiums) && typeof value.points === 'number' }
function series(value: unknown): value is TournamentSeries { return record(value) && typeof value.id === 'string' && typeof value.name === 'string' && (value.description === null || typeof value.description === 'string') && ['DRAFT','ACTIVE','COMPLETED','CANCELLED'].includes(String(value.status)) && typeof value.isOrganizer === 'boolean' && player(value.organizer) && Array.isArray(value.members) && value.members.every(member) && Array.isArray(value.events) && value.events.every(event) && Array.isArray(value.standings) && value.standings.every(standing) && typeof value.createdAt === 'string' && typeof value.updatedAt === 'string' }
export function isTournamentSeriesResponse(value: unknown): value is TournamentSeriesResponse { return record(value) && Array.isArray(value.series) && value.series.every(series) }
